version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 100
  ignore:
  - dependency-name: nunomaduro/larastan
    versions:
    - 0.6.13
    - 0.7.0
    - 0.7.1
    - 0.7.2
  - dependency-name: vimeo/psalm
    versions:
    - 4.4.1
    - 4.5.0
    - 4.5.1
    - 4.5.2
    - 4.6.0
    - 4.6.1
    - 4.6.2
    - 4.6.3
    - 4.6.4
  - dependency-name: symfony/http-kernel
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: laravel/framework
    versions:
    - 7.30.3
